---
title: "Final Project"
author: "Avi Agarwal"
date: "2023-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
dime <- read_csv("Gov 50 Final Project/dime_recipients_1979_2020.csv")
theme_set(theme_bw(base_size = 12))
library(ggthemes)
library(extrafont)
library(broom)
```

##Introduction

`
```{r}
dime_res <- dime |>
  drop_na(gwinner)
```

```{r}
dime_res_n <- dime_res |>
  filter(cycle == 2016) |>
  group_by(seat) |>
  mutate(nms = (100 * (total.receipts/median(total.receipts)))) |>
  drop_na(nms) |>
  mutate(across(c(`nms`),round,2))
```

```{r}
dime_res_n <- dime_res_n |>
   mutate(`Election Outcome:` = if_else(gwinner == "W","Won", "Loss"))
dime_res_n$`Election Outcome:` <- factor(dime_res_n$`Election Outcome:`, levels = c("Won","Loss"))
```

```{r fig.height=5}
nms_gvc <- dime_res_n |>
  ggplot(aes(y = nms, x = gen.vote.pct)) + 
  geom_point(aes(color = `Election Outcome:`), alpha = 0.35) + 
  scale_y_continuous(limits = c(0,400)) + scale_color_manual(values = c("darkblue", "red3")) + 
  labs(y = "NMS Score",
       x = "% Vote Share in 2016 General Election",
       caption = "Source: Stanford Database on Ideology, Money in Politics, and Elections.",
       title = "NMS Score over Vote Share in 2016 General Election") +
  theme_economist() + 
  theme(plot.caption = element_text(hjust = 0, size = 8, face = "italic")) + 
  theme(text=element_text(family="Calibri")) +
  theme(axis.title.x = element_text(margin = margin(t = 10, b = 10))) +
  theme(axis.title.y = element_text(margin = margin(r = 15))) +
  theme(legend.title = element_text(size = 14, face = "bold")) +
  theme(plot.title = element_text(hjust = 0.2)) +
  geom_hline(yintercept = 100, size = 1, color = "black") 
nms_gvc
```

```{r}
seat_bar <- dime_res_n |>
  filter(seat == "federal:senate" | seat == "federal:house") |>
  filter(nms >= 100) |>
  group_by(seat) |>
  mutate(win_bin = if_else(gwinner == "W", 1,0)) |>
  summarize(prop_win = mean(win_bin)) |>
  rename(Seat = seat) |>
  mutate(across(c(`prop_win`),round,2)) |>
  mutate(Seat = if_else(Seat == "federal:house", "House of Representatives", "Senate"))
seat_bar

bar <- seat_bar |> 
  ggplot(aes(x = Seat, y = prop_win, fill = Seat )) + 
  geom_bar(stat='identity', width=.5) + 
  labs(x = "Seat Sought", 
       y = "Proportion of Candidates that Won",
       caption = "Source: Stanford Database on Ideology, Money in Politics, and Elections.", 
       title = "Proportion of Candidates that Won that Median\nContribution Raised relative to Sought Seat") + scale_fill_manual(values = c("steelblue", "red3")) + 
  geom_hline(yintercept = 0.5, size = 1) + 
  geom_text(aes(label = prop_win), vjust = 1.5, colour = "white",family="Calibri" ) +  
  theme_economist() +
  theme(legend.position = "none") + 
  theme(axis.title.y = element_text(margin = margin(r = 15))) + 
  theme(axis.title.x = element_text(margin = margin(t = 10, b = 10))) + 
  theme(title = element_text(margin = margin(b = 5))) + 
  theme(plot.caption = element_text(hjust = 0, size = 8, face = "italic")) +
  theme(text=element_text(family="Calibri")) 
bar
```

```{r}
dime_reg <- dime_res_n |>
  mutate(win_bin = if_else(gwinner == "W", 1,0)) |>
  filter(seat == "federal:senate" | seat == "federal:house") |>
  mutate(Seat = if_else(seat == "federal:house", "House of Representatives", "Senate")) |>
  mutate(nms_w = if_else(nms >= 100, 1, 0))
reg <- lm(win_bin ~ nms_w + Seat, data = dime_reg)
var_labels <- c(
  "(Intercept)" = "Win Prop. under NMS",
  "nms_w" = "Win Prop. for House Candidate over NMS",
  "SeatSenate" = "Senate"
)
modelsummary::modelsummary(
reg ,coef_map = var_labels,
gof_map = c("nobs", "r.squared", "adj.r.squared"))
```