---
title: "Gov 50 Final Project"
author: "Avi Agarwal"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Final Project Milestone 2

To what extent can exceeding the average donation amount for a particular political office be considered a reliable indicator of success in the election for that office? In this study, I will examine the political offices with the highest general election success rate for candidates who raised 25% more than the average raised by candidates running for the same office. I hypothesize that there will be a trend that indicates money will be most impactful in the most minor elections (with the lowest eligible voters) since people will often have stronger opinions concerning federal elections. As a result, marketing efforts driven by donations will have a lower effect. My sample will be all election contributions for the 2020 general election for 13 political offices (3 federal and 10 state). My unit of analysis is a winning political candidate in the 2020 election. The explanatory variable is the political office the candidate is running for. This is the “seat” variable in the dataset and is coded as unique character strings. The outcome variable is whether a candidate received 25% more contributions than the average received for the political office they are running for. This variable in the dataset is “total.receipts” and is currently coded as the total contributions received, but I can easily create a new binary variable based on if a candidate received 25% more contributions than the average received for the political office they are running for (1 if yes, 0 if no). The observed pattern that would prove my hypothesis is if successful low-level electoral candidates (those running for lower chamber state legislature) correlate most with above-average donations received. Three scenarios disprove my hypothesis. The first would be no correlation between above-average donations received and electoral victory. The second would be winning federal electoral candidates more correlated with above-average donations received than minor state electoral candidates. The last would be no trend based on election size in the correlation between above-average donations received and election success. This data comes from Stanford's “Database on Ideology, Money in Politics, and Elections."